### ISSUE TITLE
Remove Phi: Maybe delete load/store codes before remove phi ? 

### ISSUE THREAD

**Issue by lfkdsk** [m-carrasco/net-ssa#16]
https://github.com/m-carrasco/net-ssa/blob/e00ba50350b4f17bb9558dd85332d16b08d7854e/net-ssa-lib/analyses/Ssa.cs#L64

In this logic, it seems that some phi nodes which resolve relationship between reuse different blocks' variables are also be removed. But its relationship is like hidden behind load/store code and localvars become special reuse var names in a global SSA formal IR. 

Maybe we could delete load/store codes and replace to some `redef code` before SSA remove phi node? And recompute local var , insert store/load when cli want to dump csharp ir.

**Comment by m-carrasco** [comment]
Dear @lfkdsk,

> In this logic, it seems that some phi nodes which resolve relationship between reuse different blocks' variables are also be removed.

Yes, you're correct. It only deletes phi nodes _that are never used_. They appear because register names are available at a method scope anywhere. One example of it is described in the method's comment (right below the line you shared).

> But its relationship is like hidden behind load/store code and localvars become special reuse var names in a global SSA formal IR.

In CIL, local variables are only accessed by load and store instructions. However, they are not promoted to registers in my representation. Thus, they are not transformed into SSA. This is because exceptional data flow may happen through local variables and it is not easy to model it. 

> Maybe we could delete load/store codes and replace to some redef code before SSA remove phi node? And recompute local var , insert store/load when cli want to dump csharp it.

As I've just mentioned, local variables are not promoted to registers due to exceptional data flow. However, it is on my plans to promote local variables that are within the same "exceptional region". Roughly speaking, local variable definitions which are only used within the same protected block or exception handler. This would happen before transforming the method into SSA, but after generating the initial register-based representation. 

Let me know if I didn't understand you well!

**Comment by lfkdsk** [comment]
Thanks for reply !

> In CIL, local variables are only accessed by load and store instructions. However, they are not promoted to registers in my representation. Thus, they are not transformed into SSA. This is because exceptional data flow may happen through local variables and it is not easy to model it.

Could local vars be modeled like `LLVM local var`, and use mem2reg-like's pass logic to promote them to regs ? Such like: 

1. Emit fake alloc local var code in entry block
2. Bind these return values with load/store codes in use-def chain.
3. Use mem2reg way to promote them to regs.

**Comment by m-carrasco** [comment]
I think the short answer is that they could be modelled as LLVM-IR `alloca`. However, I find that a bit tricky because an alloca returns a pointer. We would be introducing addresses and pointers when it is not strictly required. 

I intend to perform a mem2reg optimisation but only for those local variable definitions which are in the same protected region. Otherwise, we may have redundant phi nodes due to the exceptional control flow. The exceptional flow is easy to overapproximate but not to precisely model.

**Comment by m-carrasco** [comment]
I am going to close this issue, feel free to open it again or create a new one.
